version: '3.7'

services:
  n8n:
    image: n8nio/n8n:1.95.2
    restart: always
    ports:
      - '5678:5678'
    environment:
      - N8N_BASIC_AUTH_ACTIVE=false
      - N8N_USER_MANAGEMENT_DISABLED=false
      - N8N_BASIC_AUTH_USER=admin@example.com
      - N8N_BASIC_AUTH_PASSWORD=Superadmin
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - WEBHOOK_URL=http://localhost:5678
      - N8N_CUSTOM_EXTENSIONS=/data/custom
    volumes:
      - ./n8n_data:/home/node/.n8n
      - ./n8n-custom:/data/custom
      - ./ndx.csv:/ndx.csv

